Trying to fix the "Expected { after node-type id!" problem... But introduced a new one:
ERROR: Expected a closing brace after fields of a node;expected colon in COMPONENT statement, fou
nd "(EOF)"
parser_vrmlScene: Try route
parser_vrmlScene: Try proto
Parser failed!
8da72b8 xfree at vrml_parser/CParse.c:64
trying to free null pointer
trying to free null pointer
trying to free null pointer
trying to free null pointer
trying to free null pointer
trying to free null pointer
trying to free null pointer
trying to free null pointer
trying to free null pointer
trying to free null pointer
trying to free null pointer
trying to free null pointer
trying to free null pointer
trying to free null pointer
trying to free null pointer
trying to free null pointer